In [2]:
import numpy as np

In [6]:
A = np.array([[1,3,5],[9,3,7]])
B = np.array([1,3,2])
print(B)
print(A.T)
sort_perm = np.argsort(B)
print(B[sort_perm])
print(A.T[sort_perm])

[1 3 2]
[[1 9]
 [3 3]
 [5 7]]
[1 2 3]
[[1 9]
 [5 7]
 [3 3]]
